default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/qit_development
  username: anup

test:
  <<: *default
  database: db/qit_test
  username: anup

production:
  <<: *default
  database: db/qit_production